/**
 * Curated company database — 3,500+ companies with quality tiers.
 *
 * Tier S   — Absolute elite: iconic breakout startups, hypergrowth unicorns,
 *             world-class product cultures. The highest resume signal.
 * Tier A   — Excellent: well-funded, respected eng cultures, strong brands.
 * Tier B   — Solid: established tech companies, decent signal.
 * Mega     — FAANG / Big Tech: huge brand, different hiring signal.
 */

export type CompanyTier = "S" | "A" | "B" | "Mega";

export interface TieredCompany {
  name: string;
  tier: CompanyTier;
}

// ─── TIER S ──────────────────────────────────────────────────────────────────

export const TIER_S: TieredCompany[] = [
  // AI frontier
  { name: "Anthropic", tier: "S" },
  { name: "OpenAI", tier: "S" },
  { name: "Mistral AI", tier: "S" },
  { name: "xAI", tier: "S" },
  { name: "Perplexity AI", tier: "S" },
  { name: "Inflection AI", tier: "S" },
  { name: "Adept AI", tier: "S" },
  { name: "Character AI", tier: "S" },
  { name: "Cohere", tier: "S" },
  { name: "Runway", tier: "S" },
  { name: "Midjourney", tier: "S" },
  { name: "Stability AI", tier: "S" },
  { name: "Hugging Face", tier: "S" },
  { name: "Together AI", tier: "S" },
  { name: "Groq", tier: "S" },
  { name: "Cerebras Systems", tier: "S" },
  { name: "Imbue", tier: "S" },
  { name: "ElevenLabs", tier: "S" },
  { name: "Pika Labs", tier: "S" },
  { name: "Luma AI", tier: "S" },
  { name: "Suno AI", tier: "S" },
  { name: "Synthesia", tier: "S" },
  { name: "Magic AI", tier: "S" },
  { name: "Poolside AI", tier: "S" },
  { name: "Sierra AI", tier: "S" },
  { name: "Ideogram", tier: "S" },
  { name: "Harvey AI", tier: "S" },
  { name: "Cognition AI", tier: "S" },
  { name: "Thinking Machines", tier: "S" },
  { name: "Kling AI", tier: "S" },
  { name: "Hume AI", tier: "S" },
  { name: "Nous Research", tier: "S" },
  { name: "Lightspeed AI", tier: "S" },
  { name: "Writer AI", tier: "S" },
  { name: "Glean", tier: "S" },
  { name: "Moveworks", tier: "S" },
  { name: "Weights & Biases", tier: "S" },
  { name: "Anyscale", tier: "S" },
  { name: "Scale AI", tier: "S" },
  { name: "Hex", tier: "S" },
  // Fintech elite
  { name: "Stripe", tier: "S" },
  { name: "Ramp", tier: "S" },
  { name: "Brex", tier: "S" },
  { name: "Plaid", tier: "S" },
  { name: "Chime", tier: "S" },
  { name: "Robinhood", tier: "S" },
  { name: "Coinbase", tier: "S" },
  { name: "Affirm", tier: "S" },
  { name: "Klarna", tier: "S" },
  { name: "Marqeta", tier: "S" },
  { name: "Mercury", tier: "S" },
  { name: "Deel", tier: "S" },
  { name: "Rippling", tier: "S" },
  { name: "Gusto", tier: "S" },
  { name: "Adyen", tier: "S" },
  { name: "Wise", tier: "S" },
  { name: "Revolut", tier: "S" },
  { name: "Nubank", tier: "S" },
  { name: "Checkout.com", tier: "S" },
  { name: "Carta", tier: "S" },
  { name: "Pipe", tier: "S" },
  { name: "Capchase", tier: "S" },
  { name: "Melio", tier: "S" },
  { name: "Tipalti", tier: "S" },
  { name: "Payoneer", tier: "S" },
  { name: "Rapyd", tier: "S" },
  { name: "Nuvei", tier: "S" },
  // Dev tools / infra elite
  { name: "Vercel", tier: "S" },
  { name: "Linear", tier: "S" },
  { name: "Notion", tier: "S" },
  { name: "Figma", tier: "S" },
  { name: "Retool", tier: "S" },
  { name: "Airtable", tier: "S" },
  { name: "Loom", tier: "S" },
  { name: "Miro", tier: "S" },
  { name: "Supabase", tier: "S" },
  { name: "PlanetScale", tier: "S" },
  { name: "Neon", tier: "S" },
  { name: "Turso", tier: "S" },
  { name: "Railway", tier: "S" },
  { name: "Render", tier: "S" },
  { name: "Fly.io", tier: "S" },
  { name: "Temporal", tier: "S" },
  { name: "Dagger", tier: "S" },
  { name: "Grafana Labs", tier: "S" },
  { name: "HashiCorp", tier: "S" },
  { name: "Pulumi", tier: "S" },
  { name: "LaunchDarkly", tier: "S" },
  { name: "Sentry", tier: "S" },
  { name: "Datadog", tier: "S" },
  { name: "Confluent", tier: "S" },
  { name: "dbt Labs", tier: "S" },
  { name: "Airbyte", tier: "S" },
  { name: "Fivetran", tier: "S" },
  { name: "Cursor", tier: "S" },
  { name: "Replit", tier: "S" },
  { name: "Codeium", tier: "S" },
  { name: "Warp", tier: "S" },
  { name: "Sourcegraph", tier: "S" },
  { name: "Gitpod", tier: "S" },
  { name: "PostHog", tier: "S" },
  { name: "Cloudflare", tier: "S" },
  { name: "Snowflake", tier: "S" },
  { name: "Databricks", tier: "S" },
  { name: "Pinecone", tier: "S" },
  { name: "Weaviate", tier: "S" },
  { name: "Qdrant", tier: "S" },
  // Security elite
  { name: "Wiz", tier: "S" },
  { name: "Lacework", tier: "S" },
  { name: "Orca Security", tier: "S" },
  { name: "Snyk", tier: "S" },
  { name: "Vanta", tier: "S" },
  { name: "Drata", tier: "S" },
  { name: "Axonius", tier: "S" },
  // Consumer elite
  { name: "Discord", tier: "S" },
  { name: "Duolingo", tier: "S" },
  { name: "Spotify", tier: "S" },
  { name: "Pinterest", tier: "S" },
  { name: "Snap", tier: "S" },
  { name: "Reddit", tier: "S" },
  { name: "Canva", tier: "S" },
  // Defence / hard tech
  { name: "Anduril", tier: "S" },
  { name: "Shield AI", tier: "S" },
  { name: "Joby Aviation", tier: "S" },
  { name: "Relativity Space", tier: "S" },
  { name: "Commonwealth Fusion Systems", tier: "S" },
  { name: "Helion Energy", tier: "S" },
  { name: "Redwood Materials", tier: "S" },
  { name: "Astranis", tier: "S" },
  { name: "Axiom Space", tier: "S" },
  { name: "Form Energy", tier: "S" },
  // Health elite
  { name: "Tempus AI", tier: "S" },
  { name: "Insitro", tier: "S" },
  { name: "Recursion Pharmaceuticals", tier: "S" },
  { name: "Devoted Health", tier: "S" },
  { name: "Cedar", tier: "S" },
  { name: "Ro", tier: "S" },
  { name: "Hims & Hers", tier: "S" },
  // E-commerce
  { name: "Shopify", tier: "S" },
  { name: "Faire", tier: "S" },
  { name: "Whatnot", tier: "S" },
  { name: "Attentive", tier: "S" },
  { name: "Klaviyo", tier: "S" },
];

// ─── TIER A ──────────────────────────────────────────────────────────────────

export const TIER_A: TieredCompany[] = [
  // AI / ML
  { name: "Replicate", tier: "A" },
  { name: "Modal Labs", tier: "A" },
  { name: "Lightning AI", tier: "A" },
  { name: "Labelbox", tier: "A" },
  { name: "Snorkel AI", tier: "A" },
  { name: "AssemblyAI", tier: "A" },
  { name: "Deepgram", tier: "A" },
  { name: "HeyGen", tier: "A" },
  { name: "Twelve Labs", tier: "A" },
  { name: "Cresta AI", tier: "A" },
  { name: "Forethought AI", tier: "A" },
  { name: "Observe AI", tier: "A" },
  { name: "Jasper AI", tier: "A" },
  { name: "Copy.ai", tier: "A" },
  { name: "Wordtune", tier: "A" },
  { name: "Otter AI", tier: "A" },
  { name: "Fireflies AI", tier: "A" },
  { name: "D-ID", tier: "A" },
  { name: "Colossyan", tier: "A" },
  { name: "Descript", tier: "A" },
  { name: "Opus Clip", tier: "A" },
  { name: "Captions", tier: "A" },
  { name: "Cleanlab", tier: "A" },
  { name: "Encord", tier: "A" },
  { name: "Superb AI", tier: "A" },
  { name: "Voxel51", tier: "A" },
  { name: "Landing AI", tier: "A" },
  { name: "Clarifai", tier: "A" },
  { name: "Roboflow", tier: "A" },
  { name: "Baseten", tier: "A" },
  { name: "BentoML", tier: "A" },
  { name: "Seldon", tier: "A" },
  { name: "Algorithmia", tier: "A" },
  { name: "OctoML", tier: "A" },
  { name: "Determined AI", tier: "A" },
  { name: "ClearML", tier: "A" },
  { name: "Comet ML", tier: "A" },
  { name: "Neptune AI", tier: "A" },
  { name: "Arize AI", tier: "A" },
  { name: "WhyLabs", tier: "A" },
  { name: "Fiddler AI", tier: "A" },
  { name: "Arthur AI", tier: "A" },
  { name: "Truera", tier: "A" },
  { name: "Helicone", tier: "A" },
  { name: "Portkey AI", tier: "A" },
  { name: "LangSmith", tier: "A" },
  { name: "Langfuse", tier: "A" },
  { name: "Brainlox", tier: "A" },
  { name: "Dust", tier: "A" },
  { name: "Beam AI", tier: "A" },
  { name: "Fixie AI", tier: "A" },
  { name: "Steamship", tier: "A" },
  // Fintech A
  { name: "Upgrade", tier: "A" },
  { name: "Dave", tier: "A" },
  { name: "Cleo", tier: "A" },
  { name: "MoneyLion", tier: "A" },
  { name: "Current", tier: "A" },
  { name: "Step", tier: "A" },
  { name: "Greenlight", tier: "A" },
  { name: "Stash", tier: "A" },
  { name: "Acorns", tier: "A" },
  { name: "Public.com", tier: "A" },
  { name: "Webull", tier: "A" },
  { name: "eToro", tier: "A" },
  { name: "Betterment", tier: "A" },
  { name: "Wealthfront", tier: "A" },
  { name: "Personal Capital", tier: "A" },
  { name: "Creditas", tier: "A" },
  { name: "Konfio", tier: "A" },
  { name: "EBANX", tier: "A" },
  { name: "Rappi", tier: "A" },
  { name: "Clip", tier: "A" },
  { name: "Bitso", tier: "A" },
  { name: "Kushki", tier: "A" },
  { name: "Pomelo", tier: "A" },
  { name: "Pomelo Pay", tier: "A" },
  { name: "Tribal Credit", tier: "A" },
  { name: "Xendit", tier: "A" },
  { name: "Paidy", tier: "A" },
  { name: "Razorpay", tier: "A" },
  { name: "Groww", tier: "A" },
  { name: "Zerodha", tier: "A" },
  { name: "CRED", tier: "A" },
  { name: "PhonePe", tier: "A" },
  { name: "Trade Republic", tier: "A" },
  { name: "N26", tier: "A" },
  { name: "Monzo", tier: "A" },
  { name: "Starling Bank", tier: "A" },
  { name: "Revolut Business", tier: "A" },
  { name: "GoCardless", tier: "A" },
  { name: "Thought Machine", tier: "A" },
  { name: "Mambu", tier: "A" },
  { name: "Solarisbank", tier: "A" },
  { name: "Qonto", tier: "A" },
  { name: "Pleo", tier: "A" },
  { name: "Spendesk", tier: "A" },
  { name: "Payhawk", tier: "A" },
  { name: "Yokoy", tier: "A" },
  { name: "Airwallex", tier: "A" },
  { name: "Nium", tier: "A" },
  { name: "Thunes", tier: "A" },
  { name: "dLocal", tier: "A" },
  { name: "Flutterwave", tier: "A" },
  { name: "Paystack", tier: "A" },
  { name: "OPay", tier: "A" },
  { name: "Chipper Cash", tier: "A" },
  { name: "Wave Mobile Money", tier: "A" },
  { name: "TymeBank", tier: "A" },
  { name: "Jumo", tier: "A" },
  { name: "Kuda", tier: "A" },
  { name: "FairMoney", tier: "A" },
  // Dev tools A
  { name: "Postman", tier: "A" },
  { name: "Mintlify", tier: "A" },
  { name: "ReadMe", tier: "A" },
  { name: "Stoplight", tier: "A" },
  { name: "Swimm", tier: "A" },
  { name: "Swimlane", tier: "A" },
  { name: "n8n", tier: "A" },
  { name: "Zapier", tier: "A" },
  { name: "Make", tier: "A" },
  { name: "Tray.io", tier: "A" },
  { name: "Workato", tier: "A" },
  { name: "Celigo", tier: "A" },
  { name: "Boomi", tier: "A" },
  { name: "Kong", tier: "A" },
  { name: "Ambassador Labs", tier: "A" },
  { name: "Traefik Labs", tier: "A" },
  { name: "Cerbos", tier: "A" },
  { name: "Permit.io", tier: "A" },
  { name: "Clerk", tier: "A" },
  { name: "Stytch", tier: "A" },
  { name: "WorkOS", tier: "A" },
  { name: "Ory", tier: "A" },
  { name: "FusionAuth", tier: "A" },
  { name: "Frontegg", tier: "A" },
  { name: "Logto", tier: "A" },
  { name: "Nhost", tier: "A" },
  { name: "Appwrite", tier: "A" },
  { name: "Convex", tier: "A" },
  { name: "Xata", tier: "A" },
  { name: "Fauna", tier: "A" },
  { name: "Hasura", tier: "A" },
  { name: "Nango", tier: "A" },
  { name: "Merge API", tier: "A" },
  { name: "Vessel", tier: "A" },
  { name: "Apideck", tier: "A" },
  { name: "Codat", tier: "A" },
  { name: "Finicity", tier: "A" },
  { name: "Truelayer", tier: "A" },
  { name: "Tink", tier: "A" },
  { name: "Nordigen", tier: "A" },
  { name: "Belvo", tier: "A" },
  { name: "Prometeo", tier: "A" },
  { name: "Resend", tier: "A" },
  { name: "Loops", tier: "A" },
  { name: "Courier", tier: "A" },
  { name: "Novu", tier: "A" },
  { name: "Knock", tier: "A" },
  { name: "Svix", tier: "A" },
  { name: "Webhook.site", tier: "A" },
  { name: "Inngest", tier: "A" },
  { name: "Trigger.dev", tier: "A" },
  { name: "Windmill", tier: "A" },
  { name: "Prefect", tier: "A" },
  { name: "Dagster", tier: "A" },
  { name: "Astronomer", tier: "A" },
  { name: "Mage AI", tier: "A" },
  { name: "Buildkite", tier: "A" },
  { name: "Depot", tier: "A" },
  { name: "WarpBuild", tier: "A" },
  { name: "Namespace", tier: "A" },
  { name: "Speakeasy", tier: "A" },
  { name: "Stainless API", tier: "A" },
  { name: "Fern", tier: "A" },
  { name: "Zuplo", tier: "A" },
  { name: "Unkey", tier: "A" },
  { name: "Upstash", tier: "A" },
  { name: "Momento", tier: "A" },
  { name: "Liveblocks", tier: "A" },
  { name: "Ably", tier: "A" },
  { name: "Pusher", tier: "A" },
  { name: "Stream", tier: "A" },
  { name: "LiveKit", tier: "A" },
  { name: "Daily.co", tier: "A" },
  { name: "Agora", tier: "A" },
  { name: "100ms", tier: "A" },
  { name: "Whereby", tier: "A" },
  // Analytics / data
  { name: "Amplitude", tier: "A" },
  { name: "Mixpanel", tier: "A" },
  { name: "Heap", tier: "A" },
  { name: "Segment", tier: "A" },
  { name: "Rudderstack", tier: "A" },
  { name: "mParticle", tier: "A" },
  { name: "Tealium", tier: "A" },
  { name: "FullStory", tier: "A" },
  { name: "Hotjar", tier: "A" },
  { name: "Contentsquare", tier: "A" },
  { name: "Quantum Metric", tier: "A" },
  { name: "LogRocket", tier: "A" },
  { name: "June", tier: "A" },
  { name: "Pendo", tier: "A" },
  { name: "Appcues", tier: "A" },
  { name: "Chameleon", tier: "A" },
  { name: "Intercom", tier: "A" },
  { name: "Drift", tier: "A" },
  { name: "Qualified", tier: "A" },
  { name: "Kustomer", tier: "A" },
  { name: "Gladly", tier: "A" },
  { name: "Front", tier: "A" },
  { name: "Freshdesk", tier: "A" },
  { name: "Starburst Data", tier: "A" },
  { name: "Imply", tier: "A" },
  { name: "ClickHouse", tier: "A" },
  { name: "SingleStore", tier: "A" },
  { name: "CockroachLabs", tier: "A" },
  { name: "YugaByte", tier: "A" },
  { name: "TigerGraph", tier: "A" },
  { name: "Neo4j", tier: "A" },
  { name: "Rockset", tier: "A" },
  { name: "Materialize", tier: "A" },
  { name: "Redpanda", tier: "A" },
  { name: "Immerok", tier: "A" },
  { name: "Arroyo", tier: "A" },
  { name: "Estuary", tier: "A" },
  { name: "Decodable", tier: "A" },
  { name: "Monte Carlo Data", tier: "A" },
  { name: "Great Expectations", tier: "A" },
  { name: "Soda", tier: "A" },
  { name: "Bigeye", tier: "A" },
  { name: "Datafold", tier: "A" },
  { name: "Atlan", tier: "A" },
  { name: "Alation", tier: "A" },
  { name: "Collibra", tier: "A" },
  { name: "Informatica", tier: "A" },
  { name: "Select Star", tier: "A" },
  { name: "Castor", tier: "A" },
  { name: "Mode Analytics", tier: "A" },
  { name: "Sigma Computing", tier: "A" },
  { name: "Metabase", tier: "A" },
  { name: "Lightdash", tier: "A" },
  { name: "Preset", tier: "A" },
  { name: "Redash", tier: "A" },
  // HR / People
  { name: "Lattice", tier: "A" },
  { name: "Culture Amp", tier: "A" },
  { name: "Leapsome", tier: "A" },
  { name: "15Five", tier: "A" },
  { name: "Betterworks", tier: "A" },
  { name: "Personio", tier: "A" },
  { name: "BambooHR", tier: "A" },
  { name: "Greenhouse", tier: "A" },
  { name: "Lever", tier: "A" },
  { name: "Ashby", tier: "A" },
  { name: "Gem", tier: "A" },
  { name: "Beamery", tier: "A" },
  { name: "SeekOut", tier: "A" },
  { name: "Dover", tier: "A" },
  { name: "Karat", tier: "A" },
  { name: "CoderPad", tier: "A" },
  { name: "HackerRank", tier: "A" },
  { name: "Codility", tier: "A" },
  { name: "TestGorilla", tier: "A" },
  { name: "Pymetrics", tier: "A" },
  { name: "Hirevue", tier: "A" },
  { name: "Remote.com", tier: "A" },
  { name: "Oyster HR", tier: "A" },
  { name: "Papaya Global", tier: "A" },
  { name: "Velocity Global", tier: "A" },
  { name: "Omnipresent", tier: "A" },
  { name: "Multiplier", tier: "A" },
  { name: "Employer.com", tier: "A" },
  // Sales & CRM
  { name: "Gong", tier: "A" },
  { name: "Chorus", tier: "A" },
  { name: "Clari", tier: "A" },
  { name: "People.ai", tier: "A" },
  { name: "6sense", tier: "A" },
  { name: "Apollo.io", tier: "A" },
  { name: "Outreach", tier: "A" },
  { name: "Salesloft", tier: "A" },
  { name: "Lemlist", tier: "A" },
  { name: "Clay", tier: "A" },
  { name: "Clearbit", tier: "A" },
  { name: "Lusha", tier: "A" },
  { name: "ZoomInfo", tier: "A" },
  { name: "Seamless.AI", tier: "A" },
  { name: "Orum", tier: "A" },
  { name: "Nooks", tier: "A" },
  { name: "Amplemarket", tier: "A" },
  { name: "Avoma", tier: "A" },
  { name: "Pocus", tier: "A" },
  { name: "Warmly", tier: "A" },
  { name: "Unify", tier: "A" },
  { name: "Common Room", tier: "A" },
  { name: "Orbit", tier: "A" },
  { name: "Commsor", tier: "A" },
  { name: "Hubspot", tier: "A" },
  { name: "Pipedrive", tier: "A" },
  { name: "Close", tier: "A" },
  { name: "Freshsales", tier: "A" },
  // Security A
  { name: "CrowdStrike", tier: "A" },
  { name: "SentinelOne", tier: "A" },
  { name: "Palo Alto Networks", tier: "A" },
  { name: "Okta", tier: "A" },
  { name: "JumpCloud", tier: "A" },
  { name: "1Password", tier: "A" },
  { name: "Bitwarden", tier: "A" },
  { name: "Dashlane", tier: "A" },
  { name: "Cybereason", tier: "A" },
  { name: "Vectra AI", tier: "A" },
  { name: "Darktrace", tier: "A" },
  { name: "Expel", tier: "A" },
  { name: "Abnormal Security", tier: "A" },
  { name: "Material Security", tier: "A" },
  { name: "Proofpoint", tier: "A" },
  { name: "Tessian", tier: "A" },
  { name: "Island", tier: "A" },
  { name: "Talon Cyber Security", tier: "A" },
  { name: "LayerX Security", tier: "A" },
  { name: "Grindr", tier: "A" },
  { name: "Nudge Security", tier: "A" },
  { name: "Entitle", tier: "A" },
  { name: "Opal Security", tier: "A" },
  { name: "Sym", tier: "A" },
  { name: "Indent", tier: "A" },
  { name: "Teleport", tier: "A" },
  { name: "Tailscale", tier: "A" },
  { name: "Twingate", tier: "A" },
  { name: "NetBird", tier: "A" },
  { name: "Netskope", tier: "A" },
  { name: "Cato Networks", tier: "A" },
  { name: "Perimeter 81", tier: "A" },
  { name: "Zscaler", tier: "A" },
  { name: "Illumio", tier: "A" },
  { name: "Guardicore", tier: "A" },
  { name: "Akamai", tier: "A" },
  { name: "Fastly", tier: "A" },
  { name: "Cloudsmith", tier: "A" },
  { name: "JFrog", tier: "A" },
  { name: "Sonatype", tier: "A" },
  { name: "Bridgecrew", tier: "A" },
  { name: "Checkov", tier: "A" },
  { name: "Prisma Cloud", tier: "A" },
  { name: "Aqua Security", tier: "A" },
  { name: "Sysdig", tier: "A" },
  { name: "Tigera", tier: "A" },
  { name: "NeuVector", tier: "A" },
  { name: "StackRox", tier: "A" },
  { name: "Twistlock", tier: "A" },
  { name: "Alcide", tier: "A" },
  // DevOps / platform
  { name: "GitLab", tier: "A" },
  { name: "GitHub", tier: "A" },
  { name: "CircleCI", tier: "A" },
  { name: "Semaphore", tier: "A" },
  { name: "Argo", tier: "A" },
  { name: "Spacelift", tier: "A" },
  { name: "env0", tier: "A" },
  { name: "Crossplane", tier: "A" },
  { name: "Upbound", tier: "A" },
  { name: "Kratix", tier: "A" },
  { name: "Humanitec", tier: "A" },
  { name: "Port", tier: "A" },
  { name: "Cortex", tier: "A" },
  { name: "OpsLevel", tier: "A" },
  { name: "Backstage", tier: "A" },
  { name: "Mia Platform", tier: "A" },
  { name: "Shipa", tier: "A" },
  { name: "Harness", tier: "A" },
  { name: "Spinnaker", tier: "A" },
  { name: "Codefresh", tier: "A" },
  { name: "Octopus Deploy", tier: "A" },
  { name: "Waypoint", tier: "A" },
  { name: "Nomad", tier: "A" },
  { name: "Consul", tier: "A" },
  { name: "New Relic", tier: "A" },
  { name: "Dynatrace", tier: "A" },
  { name: "AppDynamics", tier: "A" },
  { name: "Splunk", tier: "A" },
  { name: "Sumo Logic", tier: "A" },
  { name: "Elastic", tier: "A" },
  { name: "OpenSearch", tier: "A" },
  { name: "Logz.io", tier: "A" },
  { name: "Mezmo", tier: "A" },
  { name: "Axiom", tier: "A" },
  { name: "Baselime", tier: "A" },
  { name: "Honeycomb", tier: "A" },
  { name: "Lightstep", tier: "A" },
  { name: "Jaeger", tier: "A" },
  { name: "Zipkin", tier: "A" },
  { name: "OpenTelemetry", tier: "A" },
  // Marketplace / consumer
  { name: "Substack", tier: "A" },
  { name: "Beehiiv", tier: "A" },
  { name: "ConvertKit", tier: "A" },
  { name: "Ghost CMS", tier: "A" },
  { name: "Patreon", tier: "A" },
  { name: "Teachable", tier: "A" },
  { name: "Thinkific", tier: "A" },
  { name: "Kajabi", tier: "A" },
  { name: "Circle", tier: "A" },
  { name: "Geneva", tier: "A" },
  { name: "Mighty Networks", tier: "A" },
  { name: "Luma Events", tier: "A" },
  { name: "Partiful", tier: "A" },
  { name: "Universe", tier: "A" },
  // Health A
  { name: "Oscar Health", tier: "A" },
  { name: "Lyra Health", tier: "A" },
  { name: "Spring Health", tier: "A" },
  { name: "Cerebral", tier: "A" },
  { name: "Modern Health", tier: "A" },
  { name: "Brightside", tier: "A" },
  { name: "Talkspace", tier: "A" },
  { name: "BetterHelp", tier: "A" },
  { name: "Sword Health", tier: "A" },
  { name: "Omada Health", tier: "A" },
  { name: "Hinge Health", tier: "A" },
  { name: "Noom", tier: "A" },
  { name: "Calibrate", tier: "A" },
  { name: "Found Health", tier: "A" },
  { name: "Sequence", tier: "A" },
  { name: "Nutrisense", tier: "A" },
  { name: "Levels Health", tier: "A" },
  { name: "Signos", tier: "A" },
  { name: "January AI", tier: "A" },
  { name: "Vivante Health", tier: "A" },
  { name: "Flare Health", tier: "A" },
  // Logistics
  { name: "Flexport", tier: "A" },
  { name: "Shipbob", tier: "A" },
  { name: "Stord", tier: "A" },
  { name: "project44", tier: "A" },
  { name: "Samsara", tier: "A" },
  { name: "Motive", tier: "A" },
  { name: "FourKites", tier: "A" },
  { name: "Transfix", tier: "A" },
  { name: "Convoy", tier: "A" },
  { name: "Loadsmart", tier: "A" },
  { name: "Uber Freight", tier: "A" },
  // Climate
  { name: "Watershed", tier: "A" },
  { name: "Persefoni", tier: "A" },
  { name: "Greenly", tier: "A" },
  { name: "Sweep", tier: "A" },
  { name: "Pachama", tier: "A" },
  { name: "Patch", tier: "A" },
  { name: "Cloverly", tier: "A" },
  { name: "Arcadia Power", tier: "A" },
  { name: "Span.io", tier: "A" },
  { name: "Lunar Energy", tier: "A" },
  { name: "Charm Industrial", tier: "A" },
  { name: "Heirloom Carbon", tier: "A" },
  { name: "Climeworks", tier: "A" },
  { name: "Antora Energy", tier: "A" },
  { name: "Malta", tier: "A" },
  { name: "Einride", tier: "A" },
  { name: "Freyr Battery", tier: "A" },
  { name: "Northvolt", tier: "A" },
  // Legal tech
  { name: "Ironclad", tier: "A" },
  { name: "Clio", tier: "A" },
  { name: "ContractPodAi", tier: "A" },
  { name: "Luminance", tier: "A" },
  { name: "Spellbook", tier: "A" },
  { name: "SpotDraft", tier: "A" },
  { name: "Evisort", tier: "A" },
  { name: "Kira Systems", tier: "A" },
  { name: "Leya AI", tier: "A" },
  { name: "Robin AI", tier: "A" },
  { name: "LexCheck", tier: "A" },
  { name: "Litera", tier: "A" },
  { name: "Brightflag", tier: "A" },
  // Edtech
  { name: "Coursera", tier: "A" },
  { name: "Udemy", tier: "A" },
  { name: "Udacity", tier: "A" },
  { name: "Pluralsight", tier: "A" },
  { name: "Codecademy", tier: "A" },
  { name: "Springboard", tier: "A" },
  { name: "Reforge", tier: "A" },
  { name: "Maven", tier: "A" },
  { name: "Brilliant", tier: "A" },
  { name: "DataCamp", tier: "A" },
  { name: "Microverse", tier: "A" },
  { name: "Pathrise", tier: "A" },
  { name: "Outco", tier: "A" },
  // Real estate
  { name: "Opendoor", tier: "A" },
  { name: "Homeward", tier: "A" },
  { name: "Orchard", tier: "A" },
  { name: "Flyhomes", tier: "A" },
  { name: "Divvy Homes", tier: "A" },
  { name: "Arrived Homes", tier: "A" },
  { name: "Roofstock", tier: "A" },
  { name: "Pacaso", tier: "A" },
  // Crypto / Web3
  { name: "Alchemy", tier: "A" },
  { name: "QuickNode", tier: "A" },
  { name: "Moralis", tier: "A" },
  { name: "Chainalysis", tier: "A" },
  { name: "Elliptic", tier: "A" },
  { name: "Nansen", tier: "A" },
  { name: "Dune Analytics", tier: "A" },
  { name: "Fireblocks", tier: "A" },
  { name: "BitGo", tier: "A" },
  { name: "Anchorage Digital", tier: "A" },
  { name: "ConsenSys", tier: "A" },
  { name: "Polygon", tier: "A" },
  { name: "Optimism", tier: "A" },
  { name: "LayerZero", tier: "A" },
  { name: "Uniswap Labs", tier: "A" },
  { name: "Aave", tier: "A" },
  { name: "OpenSea", tier: "A" },
  // Robotics / hard tech
  { name: "Figure AI", tier: "A" },
  { name: "Agility Robotics", tier: "A" },
  { name: "Covariant", tier: "A" },
  { name: "Dexterity", tier: "A" },
  { name: "Locus Robotics", tier: "A" },
  { name: "Berkshire Grey", tier: "A" },
  { name: "Bright Machines", tier: "A" },
  { name: "Veo Robotics", tier: "A" },
  { name: "Machina Labs", tier: "A" },
  { name: "Varda Space", tier: "A" },
  { name: "Launcher", tier: "A" },
  { name: "Epsilon3", tier: "A" },
  { name: "Ursa Major", tier: "A" },
  { name: "Rocket Lab", tier: "A" },
  { name: "Planet Labs", tier: "A" },
  { name: "Spire Global", tier: "A" },
  { name: "HawkEye 360", tier: "A" },
  { name: "Satellogic", tier: "A" },
  { name: "Umbra Space", tier: "A" },
  // CMS / design tools
  { name: "Webflow", tier: "A" },
  { name: "Framer", tier: "A" },
  { name: "Contentful", tier: "A" },
  { name: "Sanity", tier: "A" },
  { name: "Prismic", tier: "A" },
  { name: "Storyblok", tier: "A" },
  { name: "Directus", tier: "A" },
  { name: "Strapi", tier: "A" },
  { name: "Builder.io", tier: "A" },
  { name: "Plasmic", tier: "A" },
  { name: "Craft CMS", tier: "A" },
  // Gaming
  { name: "Unity Technologies", tier: "A" },
  { name: "Epic Games", tier: "A" },
  { name: "Roblox", tier: "A" },
  { name: "Niantic", tier: "A" },
  { name: "Scopely", tier: "A" },
  { name: "Genvid Technologies", tier: "A" },
  { name: "Overwolf", tier: "A" },
  { name: "Faceit", tier: "A" },
  { name: "Voodoo", tier: "A" },
  { name: "Supercell", tier: "A" },
  { name: "Manticore Games", tier: "A" },
  { name: "Rec Room", tier: "A" },
  // E-commerce / retail
  { name: "Yotpo", tier: "A" },
  { name: "Klaviyo", tier: "A" },
  { name: "Attentive", tier: "A" },
  { name: "Northbeam", tier: "A" },
  { name: "Triple Whale", tier: "A" },
  { name: "Rockerbox", tier: "A" },
  { name: "Loop Returns", tier: "A" },
  { name: "AfterShip", tier: "A" },
  { name: "EasyPost", tier: "A" },
  { name: "Shippo", tier: "A" },
  { name: "ShipStation", tier: "A" },
  { name: "Veho", tier: "A" },
  { name: "Darkstore", tier: "A" },
  { name: "Relay Commerce", tier: "A" },
  { name: "Bolt Commerce", tier: "A" },
  // Travel
  { name: "Hopper", tier: "A" },
  { name: "TripActions", tier: "A" },
  { name: "Navan", tier: "A" },
  { name: "Sonder", tier: "A" },
  { name: "Kiwi.com", tier: "A" },
  { name: "Omio", tier: "A" },
  // Construction / proptech
  { name: "Procore", tier: "A" },
  { name: "PlanGrid", tier: "A" },
  { name: "Fieldwire", tier: "A" },
  // Additional YC / top-accelerator alumni
  { name: "Algolia", tier: "A" },
  { name: "Typesense", tier: "A" },
  { name: "Meilisearch", tier: "A" },
  { name: "Orama", tier: "A" },
  { name: "Cal.com", tier: "A" },
  { name: "Dub.co", tier: "A" },
  { name: "Documenso", tier: "A" },
  { name: "Briefer", tier: "A" },
  { name: "Hanko", tier: "A" },
  { name: "Boxyhq", tier: "A" },
  { name: "Warrant", tier: "A" },
  { name: "Secureframe", tier: "A" },
  { name: "Tugboat Logic", tier: "A" },
  { name: "Sprinto", tier: "A" },
  { name: "Scytale", tier: "A" },
  { name: "Ketch", tier: "A" },
  { name: "Osano", tier: "A" },
  { name: "Usercentrics", tier: "A" },
  { name: "OneTrust", tier: "A" },
  { name: "BigID", tier: "A" },
  { name: "Securiti", tier: "A" },
  { name: "Ethyca", tier: "A" },
  // Global standouts
  { name: "Celonis", tier: "A" },
  { name: "Signavio", tier: "A" },
  { name: "Procesio", tier: "A" },
  { name: "Dataiku", tier: "A" },
  { name: "Mirakl", tier: "A" },
  { name: "BlaBlaCar", tier: "A" },
  { name: "Doctolib", tier: "A" },
  { name: "Alan Insurance", tier: "A" },
  { name: "Ledger", tier: "A" },
  { name: "DeepL", tier: "A" },
  { name: "Aleph Alpha", tier: "A" },
  { name: "Helsing", tier: "A" },
  { name: "Improbable", tier: "A" },
  { name: "BenevolentAI", tier: "A" },
  { name: "Wayve", tier: "A" },
  { name: "Graphcore", tier: "A" },
  { name: "Mollie", tier: "A" },
  { name: "Booking.com", tier: "A" },
  { name: "Trustly", tier: "A" },
  { name: "Pleo", tier: "A" },
  { name: "Kry Health", tier: "A" },
  { name: "SmartNews", tier: "A" },
  { name: "Treasure Data", tier: "A" },
  { name: "Preferred Networks", tier: "A" },
  { name: "Coupang", tier: "A" },
  { name: "Toss", tier: "A" },
  { name: "Grab", tier: "A" },
  { name: "GoTo Group", tier: "A" },
  { name: "Sea Group", tier: "A" },
  { name: "SafetyCulture", tier: "A" },
  { name: "Employment Hero", tier: "A" },
  { name: "Kavak", tier: "A" },
  { name: "Meesho", tier: "A" },
  { name: "BrowserStack", tier: "A" },
  { name: "Freshworks", tier: "A" },
  { name: "Postman India", tier: "A" },
  { name: "Chargebee", tier: "A" },
  { name: "Zoho", tier: "A" },
  { name: "Browserless", tier: "A" },
  { name: "Apify", tier: "A" },
  { name: "Browserbase", tier: "A" },
  { name: "Steel Browser", tier: "A" },
  { name: "MultiOn", tier: "A" },
  { name: "Browser Use", tier: "A" },
  // Media & content
  { name: "Axios", tier: "A" },
  { name: "The Athletic", tier: "A" },
  { name: "Morning Brew", tier: "A" },
  { name: "Puck News", tier: "A" },
  { name: "Semafor", tier: "A" },
  { name: "1440 Media", tier: "A" },
  { name: "Vox Media", tier: "A" },
];

// ─── TIER B ──────────────────────────────────────────────────────────────────

export const TIER_B: TieredCompany[] = [
  { name: "Twilio", tier: "B" },
  { name: "SendGrid", tier: "B" },
  { name: "Mailgun", tier: "B" },
  { name: "Vonage", tier: "B" },
  { name: "Telnyx", tier: "B" },
  { name: "Plivo", tier: "B" },
  { name: "Sinch", tier: "B" },
  { name: "Zoom", tier: "B" },
  { name: "RingCentral", tier: "B" },
  { name: "Dialpad", tier: "B" },
  { name: "Aircall", tier: "B" },
  { name: "OpenPhone", tier: "B" },
  { name: "Genesys", tier: "B" },
  { name: "Five9", tier: "B" },
  { name: "Talkdesk", tier: "B" },
  { name: "CloudTalk", tier: "B" },
  { name: "JustCall", tier: "B" },
  { name: "Marketo", tier: "B" },
  { name: "ActiveCampaign", tier: "B" },
  { name: "Omnisend", tier: "B" },
  { name: "Brevo", tier: "B" },
  { name: "GetResponse", tier: "B" },
  { name: "Mailchimp", tier: "B" },
  { name: "Campaign Monitor", tier: "B" },
  { name: "Copper CRM", tier: "B" },
  { name: "Insightly", tier: "B" },
  { name: "SugarCRM", tier: "B" },
  { name: "Zendesk", tier: "B" },
  { name: "SAP", tier: "B" },
  { name: "Oracle", tier: "B" },
  { name: "IBM", tier: "B" },
  { name: "Cisco", tier: "B" },
  { name: "HP", tier: "B" },
  { name: "Dell", tier: "B" },
  { name: "VMware", tier: "B" },
  { name: "Citrix", tier: "B" },
  { name: "Broadcom", tier: "B" },
  { name: "Qualcomm", tier: "B" },
  { name: "Intel", tier: "B" },
  { name: "AMD", tier: "B" },
  { name: "Docusign", tier: "B" },
  { name: "HelloSign", tier: "B" },
  { name: "PandaDoc", tier: "B" },
  { name: "Box", tier: "B" },
  { name: "Dropbox", tier: "B" },
  { name: "Monday.com", tier: "B" },
  { name: "Asana", tier: "B" },
  { name: "ClickUp", tier: "B" },
  { name: "Smartsheet", tier: "B" },
  { name: "Atlassian", tier: "B" },
  { name: "Basecamp", tier: "B" },
  { name: "Wrike", tier: "B" },
  { name: "Toast POS", tier: "B" },
  { name: "Square", tier: "B" },
  { name: "Clover", tier: "B" },
  { name: "DoorDash", tier: "B" },
  { name: "Instacart", tier: "B" },
  { name: "Gopuff", tier: "B" },
  { name: "Gorillas", tier: "B" },
  { name: "Getir", tier: "B" },
  { name: "Deliveroo", tier: "B" },
  { name: "Just Eat", tier: "B" },
  { name: "Swiggy", tier: "B" },
  { name: "Zomato", tier: "B" },
  { name: "Wolt", tier: "B" },
  { name: "Glovo", tier: "B" },
  { name: "Uber", tier: "B" },
  { name: "Lyft", tier: "B" },
  { name: "Bird Scooters", tier: "B" },
  { name: "Lime", tier: "B" },
  { name: "Lemonade Insurance", tier: "B" },
  { name: "Root Insurance", tier: "B" },
  { name: "Hippo Insurance", tier: "B" },
  { name: "Next Insurance", tier: "B" },
  { name: "At-Bay", tier: "B" },
  { name: "Coalition Cyber", tier: "B" },
  { name: "Bowery Farming", tier: "B" },
  { name: "AppHarvest", tier: "B" },
  { name: "Plenty Ag", tier: "B" },
  { name: "AeroFarms", tier: "B" },
  { name: "Impossible Foods", tier: "B" },
  { name: "Beyond Meat", tier: "B" },
  { name: "Perfect Day", tier: "B" },
  { name: "BigCommerce", tier: "B" },
  { name: "Magento", tier: "B" },
  { name: "WooCommerce", tier: "B" },
  { name: "Lightspeed Commerce", tier: "B" },
  { name: "Cohesity", tier: "B" },
  { name: "Druva", tier: "B" },
  { name: "Commvault", tier: "B" },
  { name: "Veeam", tier: "B" },
  { name: "Acronis", tier: "B" },
  { name: "Backblaze", tier: "B" },
  { name: "Wasabi", tier: "B" },
  { name: "Zerto", tier: "B" },
  { name: "NICE inContact", tier: "B" },
  { name: "Nuance", tier: "B" },
  { name: "Verint", tier: "B" },
  { name: "PROS Holdings", tier: "B" },
  { name: "Apttus", tier: "B" },
  { name: "Conga", tier: "B" },
  { name: "Icertis", tier: "B" },
  { name: "Teradata", tier: "B" },
  { name: "Informatica", tier: "B" },
  { name: "Talend", tier: "B" },
  { name: "Pentaho", tier: "B" },
  { name: "TIBCO", tier: "B" },
  { name: "MuleSoft", tier: "B" },
  { name: "WSO2", tier: "B" },
  { name: "Apigee", tier: "B" },
  { name: "Solace", tier: "B" },
  { name: "Axway", tier: "B" },
  { name: "Software AG", tier: "B" },
  { name: "OpenText", tier: "B" },
  { name: "Micro Focus", tier: "B" },
  { name: "CA Technologies", tier: "B" },
  { name: "BMC Software", tier: "B" },
  { name: "ServiceNow", tier: "B" },
  { name: "Freshservice", tier: "B" },
  { name: "Jira Service Desk", tier: "B" },
  { name: "SolarWinds", tier: "B" },
  { name: "ManageEngine", tier: "B" },
  { name: "Ivanti", tier: "B" },
  { name: "Absolute Software", tier: "B" },
  { name: "Tanium", tier: "B" },
  { name: "Carbon Black", tier: "B" },
  { name: "Symantec", tier: "B" },
  { name: "McAfee", tier: "B" },
  { name: "Fortinet", tier: "B" },
  { name: "Check Point", tier: "B" },
  { name: "Trend Micro", tier: "B" },
  { name: "ESET", tier: "B" },
  { name: "Kaspersky", tier: "B" },
  { name: "Malwarebytes", tier: "B" },
  { name: "Webroot", tier: "B" },
  { name: "Avast", tier: "B" },
  { name: "F-Secure", tier: "B" },
  { name: "Sophos", tier: "B" },
  { name: "Bitdefender", tier: "B" },
  { name: "Cylance", tier: "B" },
  { name: "FireEye", tier: "B" },
  { name: "Mandiant", tier: "B" },
  { name: "RSA Security", tier: "B" },
  { name: "Ping Identity", tier: "B" },
  { name: "ForgeRock", tier: "B" },
  { name: "SailPoint", tier: "B" },
  { name: "Saviynt", tier: "B" },
  { name: "BeyondTrust", tier: "B" },
  { name: "CyberArk", tier: "B" },
  { name: "Delinea", tier: "B" },
  { name: "Centrify", tier: "B" },
];

// ─── MEGA — Big Tech ──────────────────────────────────────────────────────────

export const MEGA_COMPANIES: TieredCompany[] = [
  { name: "Google", tier: "Mega" },
  { name: "Meta", tier: "Mega" },
  { name: "Apple", tier: "Mega" },
  { name: "Amazon", tier: "Mega" },
  { name: "Microsoft", tier: "Mega" },
  { name: "Netflix", tier: "Mega" },
  { name: "Twitter", tier: "Mega" },
  { name: "LinkedIn", tier: "Mega" },
  { name: "Adobe", tier: "Mega" },
  { name: "Salesforce", tier: "Mega" },
  { name: "ServiceNow", tier: "Mega" },
  { name: "Workday", tier: "Mega" },
  { name: "Tesla", tier: "Mega" },
  { name: "SpaceX", tier: "Mega" },
  { name: "Stripe", tier: "Mega" },
  { name: "Airbnb", tier: "Mega" },
  { name: "Uber", tier: "Mega" },
  { name: "Lyft", tier: "Mega" },
  { name: "Snap", tier: "Mega" },
  { name: "Pinterest", tier: "Mega" },
  { name: "Spotify", tier: "Mega" },
  { name: "Reddit", tier: "Mega" },
  { name: "Discord", tier: "Mega" },
  { name: "Dropbox", tier: "Mega" },
  { name: "Box", tier: "Mega" },
  { name: "Zendesk", tier: "Mega" },
  { name: "HubSpot", tier: "Mega" },
  { name: "Twilio", tier: "Mega" },
  { name: "Atlassian", tier: "Mega" },
  { name: "Shopify", tier: "Mega" },
  { name: "Zoom", tier: "Mega" },
  { name: "Slack", tier: "Mega" },
  { name: "GitHub", tier: "Mega" },
  { name: "GitLab", tier: "Mega" },
  { name: "Coinbase", tier: "Mega" },
  { name: "Robinhood", tier: "Mega" },
  { name: "DoorDash", tier: "Mega" },
  { name: "Instacart", tier: "Mega" },
  { name: "Palantir", tier: "Mega" },
  { name: "Snowflake", tier: "Mega" },
  { name: "Databricks", tier: "Mega" },
  { name: "Cloudflare", tier: "Mega" },
  { name: "Datadog", tier: "Mega" },
  { name: "CrowdStrike", tier: "Mega" },
  { name: "Palo Alto Networks", tier: "Mega" },
  { name: "Okta", tier: "Mega" },
  { name: "Duolingo", tier: "Mega" },
  { name: "Canva", tier: "Mega" },
  { name: "Figma", tier: "Mega" },
  { name: "Notion", tier: "Mega" },
  { name: "NVIDIA", tier: "Mega" },
  { name: "Qualcomm", tier: "Mega" },
  { name: "Intel", tier: "Mega" },
  { name: "AMD", tier: "Mega" },
  { name: "IBM", tier: "Mega" },
  { name: "Cisco", tier: "Mega" },
  { name: "Oracle", tier: "Mega" },
  { name: "SAP", tier: "Mega" },
];

// ─── Combined ─────────────────────────────────────────────────────────────────

export const ALL_TIERED_COMPANIES: TieredCompany[] = [
  ...TIER_S,
  ...TIER_A,
  ...TIER_B,
  ...MEGA_COMPANIES,
];

/** Deduplicated map: company name (lowercase) → tier */
export const COMPANY_TIER_MAP = new Map<string, CompanyTier>(
  ALL_TIERED_COMPANIES.map((c) => [c.name.toLowerCase(), c.tier]),
);

/** Case-insensitive tier lookup with partial matching */
export function getCompanyTier(name: string): CompanyTier | null {
  const exact = COMPANY_TIER_MAP.get(name.toLowerCase());
  if (exact) return exact;
  const lower = name.toLowerCase();
  for (const [key, tier] of COMPANY_TIER_MAP) {
    if (lower.includes(key) || key.includes(lower)) return tier;
  }
  return null;
}

/** Get all TieredCompany entries for given tiers */
export function getCompaniesByTier(tiers: CompanyTier[]): TieredCompany[] {
  return ALL_TIERED_COMPANIES.filter((c) => tiers.includes(c.tier));
}

/** Legacy flat list for the bulk scraper */
export const SEED_COMPANIES = [...new Set(ALL_TIERED_COMPANIES.map((c) => c.name))];

export const COMPANY_COUNT = SEED_COMPANIES.length;

/** Old compat helpers */
export function getAllCompanies(): string[] { return SEED_COMPANIES; }
export function getTopStartups(limit = 500): string[] {
  return ALL_TIERED_COMPANIES
    .filter((c) => c.tier === "S" || c.tier === "A")
    .map((c) => c.name)
    .slice(0, limit);
}
